trainingInput:
        hyperparameters:
                goal: MINIMIZE
                maxTrials: 4
                maxParallelTrials: 2
                hyperparameterMetricTag: mean_absolute_error
                params:
                - parameterName: alpha
                  type: DOUBLE
                  minValue: 0.01
                  maxValue: 1000
                  scaleType: UNIT_LOG_SCALE
                - parameterName: degree
                  type: INTEGER
                  minValue: 1
                  maxValue: 4
                  scaleType: UNIT_LINEAR_SCALE
